### PR TITLE
Udp fix

### PR DESCRIPTION
**Pull request by jesings**

### CODE REVIEW

**Comment by jesings** [comment]
Somehow this failed on forkandopen.c I will look into this

**Comment by jesings** [comment]
I'm rerunning because I couldn't reproduce on the server. If it was a one off we may still need to look into it.

**Comment by kapkic** [comment]
I will also look into that test case. This should only be happening 1- if there's an error on fd creation 2- if foo.txt is already present (which should've been automatically removed by suite before and after running the test cases).

**Review by rennergade — COMMENTED** [review]
Seems good.

A few dumb questions.

1. Any reason to not have the early constants not be hex for uniformity?
2. Some of these values are the same for multiple defs, is this correct? ie MSG_DONTROUTE and MSG_TRYHARD

**Comment by jesings** [comment]
As for 1 I just copied these constants from the linux kernel source, we could certainly have them in hex if you'd prefer. I therefore also know that these values are 100% correct even if some of them are duplicates.

**Comment by rennergade** [comment]
Cool. That's fine with me then!

**Comment by kapkic** [comment]
Not tagged but LGTM as well 😄

**Comment by jesings** [comment]
Second run passed so I'm not sure what's going on.

**Pull request merged**
