### PR TITLE
Link RustPOSIX verbosity to Lind

### PR DESCRIPTION
**Pull request by rennergade**
enables boolean set by lindrustinit if verbose mode is set.

### CODE REVIEW

**Review by jesings — COMMENTED** [review]
I can't say I really think this makes very much sense as an atomic bool. I think it would make a lot more sense as a synconcecell but whether or not we want to use those (they're part of the same rust library submodule as synclazy) is another question

**Comment by rennergade** [comment]
> I can't say I really think this makes very much sense as an atomic bool. I think it would make a lot more sense as a synconcecell but whether or not we want to use those (they're part of the same rust library submodule as synclazy) is another question

Ok that makes sense to me.

**Review by jesings — APPROVED** [review]
This looks a lot better.

**Review by youngfalcon — APPROVED** [review]
Looks good

**Pull request merged**
