### PR TITLE
Signal domsock

### PR DESCRIPTION
**Pull request by rennergade**
## Description
This is a joint merge of the signal and domain socket branches. These changes enable us to fully run postgres and the LAMP stack.

Fixes # (issue)
https://github.com/Lind-Project/lind_project/issues/296
https://github.com/Lind-Project/lind_project/issues/186

Domain Sockets
This changes domain sockets to use a set of lind pipe internally in user space as well as refactors networking calls to clearly demonstrate each type of socket

Signals
-     implements per thread kill mechanism wrapping pthread_kill
-     implements thread id tracking for kill
-     implements storing signal handlers and masks as well as interfacing using sigaction and sigprocmask
-     implements timer mechanism for sigalrm
-     implements SIGCHLD on cage exit as well as SIGPIPE on broken pipe

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
Full test suite with added signal tests
DS specific Rust suite tests
Full lamp stack/pgbench

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been added to a pull request and/or merged in other modules (native-client, lind-glibc, lind-project)

### CODE REVIEW

**Review by yizhuoliang — APPROVED** [review]
I went through the changes for a long while and can't find anything weird, I think this should be ready to merge!

**Review by justyoyo123 — APPROVED** [review]
The domsock changes look good to me. I probably need to spend some more time to fully understand the signals portion but from what I grasp, it makes sense.

**Review by yzhang71 — APPROVED** [review]
Most of the commits have been reviewed before, and the rest LGTM.

**Comment by kuzeyardabulut** [comment]
Everything looks good to me! Code looks clear and understandable.

**Pull request merged**
